# **Dataset Setup**

Use this dataset for all exercises:

In [ ]:
import pandas as pd
import numpy as np

data = {
    'first_name': ['Tom', np.nan, 'Hugh', 'Oprah', 'Emma'],
    'last_name': ['Hanks', 'Jackman', 'Jackman', 'Winfrey', 'Stone'],
    'age': [63, 51, 51, 66, 31],
    'sex': ['m', 'm', 'm', 'f', 'f'],
    'pre_movie_score': [8, np.nan, np.nan, 6, 7],
    'post_movie_score': [10, np.nan, np.nan, 8, 9]
}

df = pd.DataFrame(data)
df

  first_name last_name  age sex  pre_movie_score  post_movie_score
0        Tom     Hanks   63   m              8.0              10.0
1        NaN   Jackman   51   m              NaN               NaN
2       Hugh   Jackman   51   m              NaN               NaN
3      Oprah   Winfrey   66   f              6.0               8.0
4       Emma     Stone   31   f              7.0               9.0

## **Exercise 1: Detect Missing Values**

1. Display all missing values in the DataFrame.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('movie_scores.csv')

In [4]:
df.isna()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

2. Count the total number of missing values per column.

In [5]:
df.isna().sum()

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

first_name          1
last_name           0
age                 0
sex                 0
pre_movie_score     2
post_movie_score    2
dtype: int64

3. Display only rows where pre_movie_score is missing.

In [6]:
df[df['pre_movie_score'].isna()]

  first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

  first_name last_name  age sex  pre_movie_score  post_movie_score
1        NaN   Jackman   51   m              NaN               NaN
2       Hugh   Jackman   51   m              NaN               NaN

## **Exercise 2: Selecting Non-Missing Data**

1. Select all rows where first_name is not missing.

In [7]:
df[~df['first_name'].isna()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

  first_name last_name  age sex  pre_movie_score  post_movie_score
0        Tom     Hanks   63   m              8.0              10.0
2       Hugh   Jackman   51   m              NaN               NaN
3      Oprah   Winfrey   66   f              6.0               8.0
4       Emma     Stone   31   f              7.0               9.0

2. Select all rows where pre_movie_score is missing but sex is not missing.

In [25]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

  first_name last_name  age sex  pre_movie_score  post_movie_score
1        NaN   Jackman   51   m              NaN               NaN
2       Hugh   Jackman   51   m              NaN               NaN

There appears to be no such record as displayed in the question

## **Exercise 3: Drop Missing Data**

1. Drop any row that has at least one missing value.

In [26]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

  first_name last_name  age sex  pre_movie_score  post_movie_score
0        Tom     Hanks   63   m              8.0              10.0
3      Oprah   Winfrey   66   f              6.0               8.0
4       Emma     Stone   31   f              7.0               9.0

2. Drop any column that has at least one missing value.

In [30]:
df.dropna(axis=1,thresh=4)

  first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

  last_name  age sex
0     Hanks   63   m
1   Jackman   51   m
2   Jackman   51   m
3   Winfrey   66   f
4     Stone   31   f

data not supporting same result

3. Drop rows that don’t have at least 4 non-missing values.

In [39]:
#df[[df.columns] == '*name']
#df.filter(regex='.*name')
df.dropna(thresh=4)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

  first_name last_name  age sex  pre_movie_score  post_movie_score
0        Tom     Hanks   63   m              8.0              10.0
2       Hugh   Jackman   51   m              NaN               NaN
3      Oprah   Winfrey   66   f              6.0               8.0
4       Emma     Stone   31   f              7.0               9.0

## **Exercise 4: Fill Missing Data**

1. Fill all missing values in the DataFrame with "Missing".

In [41]:
df.fillna('Missing')

  first_name last_name      age      sex pre_movie_score post_movie_score
0        Tom     Hanks     63.0        m             8.0             10.0
1    Missing   Missing  Missing  Missing         Missing          Missing
2       Hugh   Jackman     51.0        m         Missing          Missing
3      Oprah   Winfrey     66.0        f             6.0              8.0
4       Emma     Stone     31.0        f             7.0              9.0

  first_name last_name  age sex pre_movie_score post_movie_score
0        Tom     Hanks   63   m             8.0             10.0
1    Missing   Jackman   51   m         Missing          Missing
2       Hugh   Jackman   51   m         Missing          Missing
3      Oprah   Winfrey   66   f             6.0              8.0
4       Emma     Stone   31   f             7.0              9.0

2. Fill missing values in the first_name column with "Empty".

In [43]:
df.loc[1]

first_name          NaN
last_name           NaN
age                 NaN
sex                 NaN
pre_movie_score     NaN
post_movie_score    NaN
Name: 1, dtype: object

In [45]:
df.loc[1]['age']

np.float64(nan)

In [51]:
df.iloc[2]

first_name             Hugh
last_name           Jackman
age                    51.0
sex                       m
pre_movie_score         NaN
post_movie_score        NaN
Name: 2, dtype: object

3. Fill missing numeric columns (pre_movie_score, post_movie_score) with their column mean.

In [65]:

#df=pd.read_csv('movie_scores.csv')
#df['pre_movie_score'].fillna(df['pre_movie_score'].mean(),inplace=True)
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

  first_name last_name  age sex  pre_movie_score  post_movie_score
0        Tom     Hanks   63   m              8.0              10.0
1      Empty   Jackman   51   m              7.0               9.0
2       Hugh   Jackman   51   m              7.0               9.0
3      Oprah   Winfrey   66   f              6.0               8.0
4       Emma     Stone   31   f              7.0               9.0

## **Exercise 5: Interpolation**

1. Create a new Series:

In [66]:
tickets = pd.Series({'first':100, 'business':np.nan, 'economy-plus':50, 'economy':30})

2. Interpolate missing values using linear interpolation.

In [68]:
tickets.interpolate(method='linear')
#tickets

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64

3. Interpolate missing values using spline interpolation (order=2).

    - Hint: reset the index first to numeric.

In [79]:
#tickets.reset_index(drop=True,inplace=True)
tickets.interpolate(method='spline',order=2)
#tickets.info()

0    100.000000
1     73.333333
2     50.000000
3     30.000000
dtype: float64

0    100.000000
1     73.333333
2     50.000000
3     30.000000
dtype: float64

## **Exercise 6: Advanced Challenge**

1. Create a DataFrame where age has missing values at random positions.

In [84]:
df.iloc[1]['last_name']

nan

In [87]:
df.loc[1,'last_name']='catman'

In [88]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN    catman   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [89]:
df.loc[2,'age']=pd.NA
df.loc[4,'age']=pd.NA

In [90]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN    catman   NaN  NaN              7.0               NaN
2       Hugh   Jackman   NaN    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone   NaN    f              7.0               9.0

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1      Empty   Jackman   NaN   m              7.0               9.0
2       Hugh   Jackman  51.0   m              7.0               9.0
3      Oprah   Winfrey   NaN   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

2. Fill missing age values using forward fill.

In [93]:
df['age'].ffill(inplace=True)

/tmp/ipykernel_264347/2200393203.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].ffill(inplace=True)

In [94]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN    catman  63.0  NaN              7.0               NaN
2       Hugh   Jackman  63.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  66.0    f              7.0               9.0

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1      Empty   Jackman  63.0   m              7.0               9.0
2       Hugh   Jackman  51.0   m              7.0               9.0
3      Oprah   Winfrey  51.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

3. Fill missing pre_movie_score values using backward fill.

In [95]:
df=pd.read_csv('movie_scores.csv')

In [96]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [97]:
df['pre_movie_score'].bfill(inplace=True)

/tmp/ipykernel_264347/1352071003.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pre_movie_score'].bfill(inplace=True)

In [98]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              6.0               NaN
2       Hugh   Jackman  51.0    m              6.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1      Empty   Jackman   NaN   m              7.0               9.0
2       Hugh   Jackman  51.0   m              7.0               9.0
3      Oprah   Winfrey   NaN   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

### **Discuss: Which method (drop, fill, interpolate) is best for this dataset?**

Where most of the row was missing it should be purged

the age field can be interpolated assuming the neighbors are members of a family

The pre movie score can copy the correlation between the post movie score and the pre movie score where the values are available