# **Handling Missing**

Real-world datasets often contain missing values. Many statistical methods and machine learning models **cannot handle missing data**, so we must decide how to deal with it.

In Pandas, missing values usually appear as:
- `NaN` (Not a Number) for numeric data
- `pd.NaT` for missing datetime values

There is **no single correct solution** for handling missing data. The best choice depends on the dataset, the problem, and the trade-offs you are willing to make.

## **Main Options for Handling Missing Data**

### **Keep Missing Data (Do Nothing)**

**Description:**   Leave missing values as `NaN`.

**Pros:**
- Easiest option.
- Does not change or manipulate the original data.

**Cons:**
- Many machine learning models cannot work with missing values.
- You may lose useful information if a reasonable replacement exists.

This can be acceptable for exploratory analysis or models that explicitly support missing values.


| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | 90             | 78         |
| S002       | NaN         | 95             | 85         |
| S003       | 7           | NaN            | NaN        |
| S004       | 4           | 85             | 72         |
| S005       | NaN         | 88             | 88         |
| S006       | 6           | 92             | 80         |

<br><br>

### **Drop Missing Data**

**Description:** Remove rows or columns that contain missing values.

**Pros:**

- Simple and fast.
- Pandas allows rule-based dropping (e.g., drop rows with too many missing values).

**Cons:**

- Can remove a large portion of the dataset.
- May limit future models if dropped features become available later.

<br>

| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | 90             | 78         |
| S004       | 4           | 85             | 72         |
| S006       | 6           | 92             | 80         |

<br>

**When to drop rows:** When a row is missing most of its information.


| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | NA             | NA         |
| S004       | 4           | 85             | 72         |
| S006       | 6           | 92             | 80         |

<br>

Note: However you need to consider by dropping that row, what percentage of data you are loosing


**When to drop columns:** When most rows are missing that feature.


| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | 90             | NA         |
| S004       | 4           | 85             | NA         |
| S006       | 6           | 92             | 80         |

<br><br>

### **Fill (Replace) Missing Data**

**Description:** Replace missing values with reasonable estimates.

**Pros:**

- Preserves more data.
- Often necessary for machine learning.

**Cons:**

- Requires assumptions.
- You are technically "making up" values.

<br>

**Common Strategies**

 - **Fill with a constant**
 - **Fill placeholders with meaningful values**
 - **Fill with statistical values:** Filled values could be based on averages, medians, or domain knowledge.

<br>

| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | 90             | 78         |
| S002       | 5.5         | 95             | 85         |
| S003       | 7           | 90             | 80.6       |
| S004       | 4           | 85             | 72         |
| S005       | 5.5         | 88             | 88         |
| S006       | 6           | 92             | 80         |

<br>


 - **Interpolate Missing Data:** Estimate missing values using nearby values.

<br>

| student_id | study_hours | attendance (%) | exam_score |
|------------|-------------|----------------|------------|
| S001       | 5           | 90             | 78         |
| S002       | 6           | 95             | 85         |
| S003       | 7           | 90             | 81         |
| S004       | 4           | 85             | 72         |
| S005       | 5           | 88             | 88         |
| S006       | 6           | 92             | 80         |

<br>

  Best for:
  - Time series
  - Ordered numeric data

  Cons:
  - Requires strong assumptions.
  - Not appropriate for unordered datasets.

### **Key Takeaways**

- Dropping missing data can remove too much information.
- Filling missing values preserves data but introduces assumptions.
- Interpolation should only be used when row order is meaningful.

There is no single correct strategy — the best choice depends on context.

# **Handling Missing Data in Pandas**

<br>

## **1. Understanding Missing Data**

Pandas represents missing values in different ways depending on the data type:

| Representation | Data Type | Notes                                                                      |
| -------------- | --------- | -------------------------------------------------------------------------- |
| `np.nan`       | float     | Standard NumPy NaN for numeric data                                        |
| `None`         | object    | Python None for object types                                               |
| `pd.NaT`       | datetime  | Missing datetime values                                                    |
| `pd.NA`        | new types | Unified missing indicator for nullable integer, boolean, and string dtypes |

In [ ]:
import numpy as np
import pandas as pd

np.nan      # float missing value
pd.NA       # nullable data type missing value
pd.NaT      # datetime missing value

NaT

**Important:** Avoid direct comparisons with missing values. For example:

In [ ]:
myvar = np.nan

In [ ]:
myvar == np.nan    # False

False

In [ ]:
myvar in [np.nan]  # True

True

In [ ]:
myvar is np.nan    # True

True

Missing values are “unknown,” so logic comparisons may not behave as expected.

## **2. Example Dataset**
Suppose we have a dataset where people scored actors before and after watching their movies:

In [ ]:
df = pd.read_csv('movie_scores.csv')
df.head()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
import pandas as pd
import numpy as np

## **3. Detecting Missing Values**

**Check for missing values:**

In [ ]:
df.isnull()    # True where values are missing

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
df.notnull()   # True where values exist

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

**Select rows with non-missing values:**

In [ ]:
df[df['first_name'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**Select rows with missing pre_movie_score but known sex:**

In [ ]:
df[(df['pre_movie_score'].isnull()) & (df['sex'].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

## **4. Dropping Missing Data**
**Drop rows with any missing values:**

In [ ]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**Drop columns with any missing values:**

In [ ]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

**Drop rows only if a minimum number of non-NA values is present:**

In [ ]:
df.dropna(thresh=4)  # Keep rows with at least 4 non-NA values

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

**Define in which columns to look for missing values:**

In [ ]:
df.dropna(subset=['last_name'])

**Tip:** Check help(df.dropna) for more options like subset, how, and inplace.

## **5. Filling Missing Data**

You can replace missing values with a fixed value or computed statistics:

**Fill with a constant value:**

In [ ]:
df.fillna("NEW VALUE!")

,first_name,last_name,age,sex,pre_movie_score,post_movie_score
0,Tom,Hanks,63.0,m,8.0,10.0
1,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!
2,Hugh,Jackman,51.0,m,NEW VALUE!,NEW VALUE!
3,Oprah,Winfrey,66.0,f,6.0,8.0
4,Emma,Stone,31.0,f,7.0,9.0

**Fill a specific column:**

In [ ]:
df['first_name'] = df['first_name'].fillna("Empty")

In [ ]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(0)

**Fill numeric missing values with the mean:**

In [ ]:
df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

**Fill all numeric columns with their respective means:**

In [ ]:
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

## **6. Interpolating Missing Data**

Interpolation estimates missing values based on neighboring data. Use this method carefully—it should make sense for your dataset.

In [ ]:
airline_tix = {'first':100, 'business':np.nan, 'economy-plus':50, 'economy':30}
ser = pd.Series(airline_tix)

ser.interpolate()                # Linear interpolation
ser.interpolate(method='linear')

first           100.0
business         75.0
economy-plus     50.0
economy          30.0
dtype: float64

## **7. Key Takeaways**

- pd.NA is a unified missing value for multiple data types.

- Avoid direct comparison between missing values.

- Use isnull()/notnull() to detect missing data.

- Drop rows or columns with dropna() when appropriate.

- Fill missing values with fillna() for simple replacement or computed statistics.

- Interpolate only if it makes sense for your dataset.